language: elixir
matrix:
  include:
    - node_js: 6.11.4
      before_install:
        - nvm install 6.11.4
        - npm i -g npm
      install:
        - cd priv/react_app && npm install
      script:
        - npm run test
        - npm run build
    - elixir: 1.4.4
      otp_release: 19.3
      install:
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get
      script:
        - npm run test-backend
