language: elixir
gmatrix:
  include:
    - node_js: 6.11.0
      before_install:
        - nvm install 6.11.0
      install:
        - cd priv/react_app && npm install -g yarn && yarn install
      script:
        - npm run test
        - npm run build
    - elixir: 1.4.4
      otp_release: 19.3
      install:
        - mix local.rebar --force
        - mix local.hex --force
        - mix deps.get
      script:
        - npm run test-backend
